// Generated by jextract

package io.github.ghosthack.ffmpegffm.ffmpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class FFmpeg {

    FFmpeg() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = io.github.ghosthack.ffmpegffm.FfmpegLibs.lookup();

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;
    private static final int AV_TIME_BASE = (int)1000000L;
    /**
     * {@snippet lang=c :
     * #define AV_TIME_BASE 1000000
     * }
     */
    public static int AV_TIME_BASE() {
        return AV_TIME_BASE;
    }
    private static final int AV_LOG_ERROR = (int)16L;
    /**
     * {@snippet lang=c :
     * #define AV_LOG_ERROR 16
     * }
     */
    public static int AV_LOG_ERROR() {
        return AV_LOG_ERROR;
    }
    private static final int AV_INPUT_BUFFER_PADDING_SIZE = (int)64L;
    /**
     * {@snippet lang=c :
     * #define AV_INPUT_BUFFER_PADDING_SIZE 64
     * }
     */
    public static int AV_INPUT_BUFFER_PADDING_SIZE() {
        return AV_INPUT_BUFFER_PADDING_SIZE;
    }
    private static final int AV_DICT_IGNORE_SUFFIX = (int)2L;
    /**
     * {@snippet lang=c :
     * #define AV_DICT_IGNORE_SUFFIX 2
     * }
     */
    public static int AV_DICT_IGNORE_SUFFIX() {
        return AV_DICT_IGNORE_SUFFIX;
    }
    private static final int AVMEDIA_TYPE_UNKNOWN = (int)-1L;
    /**
     * {@snippet lang=c :
     * enum AVMediaType.AVMEDIA_TYPE_UNKNOWN = -1
     * }
     */
    public static int AVMEDIA_TYPE_UNKNOWN() {
        return AVMEDIA_TYPE_UNKNOWN;
    }
    private static final int AVMEDIA_TYPE_VIDEO = (int)0L;
    /**
     * {@snippet lang=c :
     * enum AVMediaType.AVMEDIA_TYPE_VIDEO = 0
     * }
     */
    public static int AVMEDIA_TYPE_VIDEO() {
        return AVMEDIA_TYPE_VIDEO;
    }
    private static final int AVMEDIA_TYPE_AUDIO = (int)1L;
    /**
     * {@snippet lang=c :
     * enum AVMediaType.AVMEDIA_TYPE_AUDIO = 1
     * }
     */
    public static int AVMEDIA_TYPE_AUDIO() {
        return AVMEDIA_TYPE_AUDIO;
    }
    private static final int AVMEDIA_TYPE_SUBTITLE = (int)3L;
    /**
     * {@snippet lang=c :
     * enum AVMediaType.AVMEDIA_TYPE_SUBTITLE = 3
     * }
     */
    public static int AVMEDIA_TYPE_SUBTITLE() {
        return AVMEDIA_TYPE_SUBTITLE;
    }

    private static class av_strerror {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_LONG
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_strerror");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_strerror(int errnum, char *errbuf, size_t errbuf_size)
     * }
     */
    public static FunctionDescriptor av_strerror$descriptor() {
        return av_strerror.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_strerror(int errnum, char *errbuf, size_t errbuf_size)
     * }
     */
    public static MethodHandle av_strerror$handle() {
        return av_strerror.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_strerror(int errnum, char *errbuf, size_t errbuf_size)
     * }
     */
    public static MemorySegment av_strerror$address() {
        return av_strerror.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_strerror(int errnum, char *errbuf, size_t errbuf_size)
     * }
     */
    public static int av_strerror(int errnum, MemorySegment errbuf, long errbuf_size) {
        var mh$ = av_strerror.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_strerror", errnum, errbuf, errbuf_size);
            }
            return (int)mh$.invokeExact(errnum, errbuf, errbuf_size);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_log_set_level {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_log_set_level");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void av_log_set_level(int level)
     * }
     */
    public static FunctionDescriptor av_log_set_level$descriptor() {
        return av_log_set_level.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void av_log_set_level(int level)
     * }
     */
    public static MethodHandle av_log_set_level$handle() {
        return av_log_set_level.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void av_log_set_level(int level)
     * }
     */
    public static MemorySegment av_log_set_level$address() {
        return av_log_set_level.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void av_log_set_level(int level)
     * }
     */
    public static void av_log_set_level(int level) {
        var mh$ = av_log_set_level.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_log_set_level", level);
            }
            mh$.invokeExact(level);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int AV_PIX_FMT_NONE = (int)-1L;
    /**
     * {@snippet lang=c :
     * enum AVPixelFormat.AV_PIX_FMT_NONE = -1
     * }
     */
    public static int AV_PIX_FMT_NONE() {
        return AV_PIX_FMT_NONE;
    }
    private static final int AV_PIX_FMT_BGRA = (int)28L;
    /**
     * {@snippet lang=c :
     * enum AVPixelFormat.AV_PIX_FMT_BGRA = 28
     * }
     */
    public static int AV_PIX_FMT_BGRA() {
        return AV_PIX_FMT_BGRA;
    }
    private static final int AV_PIX_FMT_GRAY16LE = (int)30L;
    /**
     * {@snippet lang=c :
     * enum AVPixelFormat.AV_PIX_FMT_GRAY16LE = 30
     * }
     */
    public static int AV_PIX_FMT_GRAY16LE() {
        return AV_PIX_FMT_GRAY16LE;
    }
    private static final int AV_PIX_FMT_RGB48LE = (int)35L;
    /**
     * {@snippet lang=c :
     * enum AVPixelFormat.AV_PIX_FMT_RGB48LE = 35
     * }
     */
    public static int AV_PIX_FMT_RGB48LE() {
        return AV_PIX_FMT_RGB48LE;
    }
    private static final int AV_PIX_FMT_RGBA64LE = (int)105L;
    /**
     * {@snippet lang=c :
     * enum AVPixelFormat.AV_PIX_FMT_RGBA64LE = 105
     * }
     */
    public static int AV_PIX_FMT_RGBA64LE() {
        return AV_PIX_FMT_RGBA64LE;
    }
    private static final int AV_CODEC_ID_JPEGXL = (int)258L;
    /**
     * {@snippet lang=c :
     * enum AVCodecID.AV_CODEC_ID_JPEGXL = 258
     * }
     */
    public static int AV_CODEC_ID_JPEGXL() {
        return AV_CODEC_ID_JPEGXL;
    }

    private static class avcodec_get_name {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_get_name");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *avcodec_get_name(enum AVCodecID id)
     * }
     */
    public static FunctionDescriptor avcodec_get_name$descriptor() {
        return avcodec_get_name.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *avcodec_get_name(enum AVCodecID id)
     * }
     */
    public static MethodHandle avcodec_get_name$handle() {
        return avcodec_get_name.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *avcodec_get_name(enum AVCodecID id)
     * }
     */
    public static MemorySegment avcodec_get_name$address() {
        return avcodec_get_name.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *avcodec_get_name(enum AVCodecID id)
     * }
     */
    public static MemorySegment avcodec_get_name(int id) {
        var mh$ = avcodec_get_name.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_get_name", id);
            }
            return (MemorySegment)mh$.invokeExact(id);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_buffer_ref {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_buffer_ref");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AVBufferRef *av_buffer_ref(const AVBufferRef *buf)
     * }
     */
    public static FunctionDescriptor av_buffer_ref$descriptor() {
        return av_buffer_ref.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AVBufferRef *av_buffer_ref(const AVBufferRef *buf)
     * }
     */
    public static MethodHandle av_buffer_ref$handle() {
        return av_buffer_ref.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AVBufferRef *av_buffer_ref(const AVBufferRef *buf)
     * }
     */
    public static MemorySegment av_buffer_ref$address() {
        return av_buffer_ref.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AVBufferRef *av_buffer_ref(const AVBufferRef *buf)
     * }
     */
    public static MemorySegment av_buffer_ref(MemorySegment buf) {
        var mh$ = av_buffer_ref.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_buffer_ref", buf);
            }
            return (MemorySegment)mh$.invokeExact(buf);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_buffer_unref {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_buffer_unref");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void av_buffer_unref(AVBufferRef **buf)
     * }
     */
    public static FunctionDescriptor av_buffer_unref$descriptor() {
        return av_buffer_unref.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void av_buffer_unref(AVBufferRef **buf)
     * }
     */
    public static MethodHandle av_buffer_unref$handle() {
        return av_buffer_unref.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void av_buffer_unref(AVBufferRef **buf)
     * }
     */
    public static MemorySegment av_buffer_unref$address() {
        return av_buffer_unref.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void av_buffer_unref(AVBufferRef **buf)
     * }
     */
    public static void av_buffer_unref(MemorySegment buf) {
        var mh$ = av_buffer_unref.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_buffer_unref", buf);
            }
            mh$.invokeExact(buf);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_dict_get {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_dict_get");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AVDictionaryEntry *av_dict_get(const AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags)
     * }
     */
    public static FunctionDescriptor av_dict_get$descriptor() {
        return av_dict_get.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AVDictionaryEntry *av_dict_get(const AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags)
     * }
     */
    public static MethodHandle av_dict_get$handle() {
        return av_dict_get.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AVDictionaryEntry *av_dict_get(const AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags)
     * }
     */
    public static MemorySegment av_dict_get$address() {
        return av_dict_get.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AVDictionaryEntry *av_dict_get(const AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags)
     * }
     */
    public static MemorySegment av_dict_get(MemorySegment m, MemorySegment key, MemorySegment prev, int flags) {
        var mh$ = av_dict_get.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_dict_get", m, key, prev, flags);
            }
            return (MemorySegment)mh$.invokeExact(m, key, prev, flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_dict_count {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_dict_count");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_dict_count(const AVDictionary *m)
     * }
     */
    public static FunctionDescriptor av_dict_count$descriptor() {
        return av_dict_count.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_dict_count(const AVDictionary *m)
     * }
     */
    public static MethodHandle av_dict_count$handle() {
        return av_dict_count.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_dict_count(const AVDictionary *m)
     * }
     */
    public static MemorySegment av_dict_count$address() {
        return av_dict_count.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_dict_count(const AVDictionary *m)
     * }
     */
    public static int av_dict_count(MemorySegment m) {
        var mh$ = av_dict_count.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_dict_count", m);
            }
            return (int)mh$.invokeExact(m);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_packet_alloc {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER    );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_packet_alloc");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AVPacket *av_packet_alloc()
     * }
     */
    public static FunctionDescriptor av_packet_alloc$descriptor() {
        return av_packet_alloc.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AVPacket *av_packet_alloc()
     * }
     */
    public static MethodHandle av_packet_alloc$handle() {
        return av_packet_alloc.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AVPacket *av_packet_alloc()
     * }
     */
    public static MemorySegment av_packet_alloc$address() {
        return av_packet_alloc.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AVPacket *av_packet_alloc()
     * }
     */
    public static MemorySegment av_packet_alloc() {
        var mh$ = av_packet_alloc.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_packet_alloc");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_packet_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_packet_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void av_packet_free(AVPacket **pkt)
     * }
     */
    public static FunctionDescriptor av_packet_free$descriptor() {
        return av_packet_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void av_packet_free(AVPacket **pkt)
     * }
     */
    public static MethodHandle av_packet_free$handle() {
        return av_packet_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void av_packet_free(AVPacket **pkt)
     * }
     */
    public static MemorySegment av_packet_free$address() {
        return av_packet_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void av_packet_free(AVPacket **pkt)
     * }
     */
    public static void av_packet_free(MemorySegment pkt) {
        var mh$ = av_packet_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_packet_free", pkt);
            }
            mh$.invokeExact(pkt);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_packet_unref {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_packet_unref");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void av_packet_unref(AVPacket *pkt)
     * }
     */
    public static FunctionDescriptor av_packet_unref$descriptor() {
        return av_packet_unref.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void av_packet_unref(AVPacket *pkt)
     * }
     */
    public static MethodHandle av_packet_unref$handle() {
        return av_packet_unref.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void av_packet_unref(AVPacket *pkt)
     * }
     */
    public static MemorySegment av_packet_unref$address() {
        return av_packet_unref.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void av_packet_unref(AVPacket *pkt)
     * }
     */
    public static void av_packet_unref(MemorySegment pkt) {
        var mh$ = av_packet_unref.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_packet_unref", pkt);
            }
            mh$.invokeExact(pkt);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_frame_alloc {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER    );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_frame_alloc");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AVFrame *av_frame_alloc()
     * }
     */
    public static FunctionDescriptor av_frame_alloc$descriptor() {
        return av_frame_alloc.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AVFrame *av_frame_alloc()
     * }
     */
    public static MethodHandle av_frame_alloc$handle() {
        return av_frame_alloc.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AVFrame *av_frame_alloc()
     * }
     */
    public static MemorySegment av_frame_alloc$address() {
        return av_frame_alloc.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AVFrame *av_frame_alloc()
     * }
     */
    public static MemorySegment av_frame_alloc() {
        var mh$ = av_frame_alloc.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_frame_alloc");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_frame_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_frame_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void av_frame_free(AVFrame **frame)
     * }
     */
    public static FunctionDescriptor av_frame_free$descriptor() {
        return av_frame_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void av_frame_free(AVFrame **frame)
     * }
     */
    public static MethodHandle av_frame_free$handle() {
        return av_frame_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void av_frame_free(AVFrame **frame)
     * }
     */
    public static MemorySegment av_frame_free$address() {
        return av_frame_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void av_frame_free(AVFrame **frame)
     * }
     */
    public static void av_frame_free(MemorySegment frame) {
        var mh$ = av_frame_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_frame_free", frame);
            }
            mh$.invokeExact(frame);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_frame_unref {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_frame_unref");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void av_frame_unref(AVFrame *frame)
     * }
     */
    public static FunctionDescriptor av_frame_unref$descriptor() {
        return av_frame_unref.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void av_frame_unref(AVFrame *frame)
     * }
     */
    public static MethodHandle av_frame_unref$handle() {
        return av_frame_unref.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void av_frame_unref(AVFrame *frame)
     * }
     */
    public static MemorySegment av_frame_unref$address() {
        return av_frame_unref.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void av_frame_unref(AVFrame *frame)
     * }
     */
    public static void av_frame_unref(MemorySegment frame) {
        var mh$ = av_frame_unref.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_frame_unref", frame);
            }
            mh$.invokeExact(frame);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int AV_HWDEVICE_TYPE_VIDEOTOOLBOX = (int)6L;
    /**
     * {@snippet lang=c :
     * enum AVHWDeviceType.AV_HWDEVICE_TYPE_VIDEOTOOLBOX = 6
     * }
     */
    public static int AV_HWDEVICE_TYPE_VIDEOTOOLBOX() {
        return AV_HWDEVICE_TYPE_VIDEOTOOLBOX;
    }
    private static final int AV_HWDEVICE_TYPE_D3D11VA = (int)7L;
    /**
     * {@snippet lang=c :
     * enum AVHWDeviceType.AV_HWDEVICE_TYPE_D3D11VA = 7
     * }
     */
    public static int AV_HWDEVICE_TYPE_D3D11VA() {
        return AV_HWDEVICE_TYPE_D3D11VA;
    }

    private static class av_hwdevice_ctx_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_hwdevice_ctx_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_hwdevice_ctx_create(AVBufferRef **device_ctx, enum AVHWDeviceType type, const char *device, AVDictionary *opts, int flags)
     * }
     */
    public static FunctionDescriptor av_hwdevice_ctx_create$descriptor() {
        return av_hwdevice_ctx_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_hwdevice_ctx_create(AVBufferRef **device_ctx, enum AVHWDeviceType type, const char *device, AVDictionary *opts, int flags)
     * }
     */
    public static MethodHandle av_hwdevice_ctx_create$handle() {
        return av_hwdevice_ctx_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_hwdevice_ctx_create(AVBufferRef **device_ctx, enum AVHWDeviceType type, const char *device, AVDictionary *opts, int flags)
     * }
     */
    public static MemorySegment av_hwdevice_ctx_create$address() {
        return av_hwdevice_ctx_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_hwdevice_ctx_create(AVBufferRef **device_ctx, enum AVHWDeviceType type, const char *device, AVDictionary *opts, int flags)
     * }
     */
    public static int av_hwdevice_ctx_create(MemorySegment device_ctx, int type, MemorySegment device, MemorySegment opts, int flags) {
        var mh$ = av_hwdevice_ctx_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_hwdevice_ctx_create", device_ctx, type, device, opts, flags);
            }
            return (int)mh$.invokeExact(device_ctx, type, device, opts, flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_hwframe_transfer_data {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_hwframe_transfer_data");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_hwframe_transfer_data(AVFrame *dst, const AVFrame *src, int flags)
     * }
     */
    public static FunctionDescriptor av_hwframe_transfer_data$descriptor() {
        return av_hwframe_transfer_data.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_hwframe_transfer_data(AVFrame *dst, const AVFrame *src, int flags)
     * }
     */
    public static MethodHandle av_hwframe_transfer_data$handle() {
        return av_hwframe_transfer_data.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_hwframe_transfer_data(AVFrame *dst, const AVFrame *src, int flags)
     * }
     */
    public static MemorySegment av_hwframe_transfer_data$address() {
        return av_hwframe_transfer_data.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_hwframe_transfer_data(AVFrame *dst, const AVFrame *src, int flags)
     * }
     */
    public static int av_hwframe_transfer_data(MemorySegment dst, MemorySegment src, int flags) {
        var mh$ = av_hwframe_transfer_data.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_hwframe_transfer_data", dst, src, flags);
            }
            return (int)mh$.invokeExact(dst, src, flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avcodec_find_decoder {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_find_decoder");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const AVCodec *avcodec_find_decoder(enum AVCodecID id)
     * }
     */
    public static FunctionDescriptor avcodec_find_decoder$descriptor() {
        return avcodec_find_decoder.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const AVCodec *avcodec_find_decoder(enum AVCodecID id)
     * }
     */
    public static MethodHandle avcodec_find_decoder$handle() {
        return avcodec_find_decoder.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const AVCodec *avcodec_find_decoder(enum AVCodecID id)
     * }
     */
    public static MemorySegment avcodec_find_decoder$address() {
        return avcodec_find_decoder.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const AVCodec *avcodec_find_decoder(enum AVCodecID id)
     * }
     */
    public static MemorySegment avcodec_find_decoder(int id) {
        var mh$ = avcodec_find_decoder.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_find_decoder", id);
            }
            return (MemorySegment)mh$.invokeExact(id);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX = 1
     * }
     */
    public static int AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX() {
        return AV_CODEC_HW_CONFIG_METHOD_HW_DEVICE_CTX;
    }

    private static class avcodec_get_hw_config {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_get_hw_config");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const AVCodecHWConfig *avcodec_get_hw_config(const AVCodec *codec, int index)
     * }
     */
    public static FunctionDescriptor avcodec_get_hw_config$descriptor() {
        return avcodec_get_hw_config.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const AVCodecHWConfig *avcodec_get_hw_config(const AVCodec *codec, int index)
     * }
     */
    public static MethodHandle avcodec_get_hw_config$handle() {
        return avcodec_get_hw_config.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const AVCodecHWConfig *avcodec_get_hw_config(const AVCodec *codec, int index)
     * }
     */
    public static MemorySegment avcodec_get_hw_config$address() {
        return avcodec_get_hw_config.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const AVCodecHWConfig *avcodec_get_hw_config(const AVCodec *codec, int index)
     * }
     */
    public static MemorySegment avcodec_get_hw_config(MemorySegment codec, int index) {
        var mh$ = avcodec_get_hw_config.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_get_hw_config", codec, index);
            }
            return (MemorySegment)mh$.invokeExact(codec, index);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int AV_STREAM_GROUP_PARAMS_TILE_GRID = (int)3L;
    /**
     * {@snippet lang=c :
     * enum AVStreamGroupParamsType.AV_STREAM_GROUP_PARAMS_TILE_GRID = 3
     * }
     */
    public static int AV_STREAM_GROUP_PARAMS_TILE_GRID() {
        return AV_STREAM_GROUP_PARAMS_TILE_GRID;
    }

    private static class avformat_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT    );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avformat_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * unsigned int avformat_version()
     * }
     */
    public static FunctionDescriptor avformat_version$descriptor() {
        return avformat_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * unsigned int avformat_version()
     * }
     */
    public static MethodHandle avformat_version$handle() {
        return avformat_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * unsigned int avformat_version()
     * }
     */
    public static MemorySegment avformat_version$address() {
        return avformat_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * unsigned int avformat_version()
     * }
     */
    public static int avformat_version() {
        var mh$ = avformat_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avformat_version");
            }
            return (int)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avformat_open_input {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avformat_open_input");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int avformat_open_input(AVFormatContext **ps, const char *url, const AVInputFormat *fmt, AVDictionary **options)
     * }
     */
    public static FunctionDescriptor avformat_open_input$descriptor() {
        return avformat_open_input.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int avformat_open_input(AVFormatContext **ps, const char *url, const AVInputFormat *fmt, AVDictionary **options)
     * }
     */
    public static MethodHandle avformat_open_input$handle() {
        return avformat_open_input.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int avformat_open_input(AVFormatContext **ps, const char *url, const AVInputFormat *fmt, AVDictionary **options)
     * }
     */
    public static MemorySegment avformat_open_input$address() {
        return avformat_open_input.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int avformat_open_input(AVFormatContext **ps, const char *url, const AVInputFormat *fmt, AVDictionary **options)
     * }
     */
    public static int avformat_open_input(MemorySegment ps, MemorySegment url, MemorySegment fmt, MemorySegment options) {
        var mh$ = avformat_open_input.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avformat_open_input", ps, url, fmt, options);
            }
            return (int)mh$.invokeExact(ps, url, fmt, options);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avformat_find_stream_info {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avformat_find_stream_info");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int avformat_find_stream_info(AVFormatContext *ic, AVDictionary **options)
     * }
     */
    public static FunctionDescriptor avformat_find_stream_info$descriptor() {
        return avformat_find_stream_info.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int avformat_find_stream_info(AVFormatContext *ic, AVDictionary **options)
     * }
     */
    public static MethodHandle avformat_find_stream_info$handle() {
        return avformat_find_stream_info.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int avformat_find_stream_info(AVFormatContext *ic, AVDictionary **options)
     * }
     */
    public static MemorySegment avformat_find_stream_info$address() {
        return avformat_find_stream_info.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int avformat_find_stream_info(AVFormatContext *ic, AVDictionary **options)
     * }
     */
    public static int avformat_find_stream_info(MemorySegment ic, MemorySegment options) {
        var mh$ = avformat_find_stream_info.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avformat_find_stream_info", ic, options);
            }
            return (int)mh$.invokeExact(ic, options);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_find_best_stream {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_find_best_stream");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_find_best_stream(AVFormatContext *ic, enum AVMediaType type, int wanted_stream_nb, int related_stream, const struct AVCodec **decoder_ret, int flags)
     * }
     */
    public static FunctionDescriptor av_find_best_stream$descriptor() {
        return av_find_best_stream.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_find_best_stream(AVFormatContext *ic, enum AVMediaType type, int wanted_stream_nb, int related_stream, const struct AVCodec **decoder_ret, int flags)
     * }
     */
    public static MethodHandle av_find_best_stream$handle() {
        return av_find_best_stream.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_find_best_stream(AVFormatContext *ic, enum AVMediaType type, int wanted_stream_nb, int related_stream, const struct AVCodec **decoder_ret, int flags)
     * }
     */
    public static MemorySegment av_find_best_stream$address() {
        return av_find_best_stream.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_find_best_stream(AVFormatContext *ic, enum AVMediaType type, int wanted_stream_nb, int related_stream, const struct AVCodec **decoder_ret, int flags)
     * }
     */
    public static int av_find_best_stream(MemorySegment ic, int type, int wanted_stream_nb, int related_stream, MemorySegment decoder_ret, int flags) {
        var mh$ = av_find_best_stream.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_find_best_stream", ic, type, wanted_stream_nb, related_stream, decoder_ret, flags);
            }
            return (int)mh$.invokeExact(ic, type, wanted_stream_nb, related_stream, decoder_ret, flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_read_frame {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_read_frame");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_read_frame(AVFormatContext *s, AVPacket *pkt)
     * }
     */
    public static FunctionDescriptor av_read_frame$descriptor() {
        return av_read_frame.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_read_frame(AVFormatContext *s, AVPacket *pkt)
     * }
     */
    public static MethodHandle av_read_frame$handle() {
        return av_read_frame.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_read_frame(AVFormatContext *s, AVPacket *pkt)
     * }
     */
    public static MemorySegment av_read_frame$address() {
        return av_read_frame.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_read_frame(AVFormatContext *s, AVPacket *pkt)
     * }
     */
    public static int av_read_frame(MemorySegment s, MemorySegment pkt) {
        var mh$ = av_read_frame.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_read_frame", s, pkt);
            }
            return (int)mh$.invokeExact(s, pkt);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_seek_frame {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT,
            FFmpeg.C_LONG_LONG,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_seek_frame");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_seek_frame(AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
     * }
     */
    public static FunctionDescriptor av_seek_frame$descriptor() {
        return av_seek_frame.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_seek_frame(AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
     * }
     */
    public static MethodHandle av_seek_frame$handle() {
        return av_seek_frame.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_seek_frame(AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
     * }
     */
    public static MemorySegment av_seek_frame$address() {
        return av_seek_frame.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_seek_frame(AVFormatContext *s, int stream_index, int64_t timestamp, int flags)
     * }
     */
    public static int av_seek_frame(MemorySegment s, int stream_index, long timestamp, int flags) {
        var mh$ = av_seek_frame.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_seek_frame", s, stream_index, timestamp, flags);
            }
            return (int)mh$.invokeExact(s, stream_index, timestamp, flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avformat_close_input {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avformat_close_input");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void avformat_close_input(AVFormatContext **s)
     * }
     */
    public static FunctionDescriptor avformat_close_input$descriptor() {
        return avformat_close_input.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void avformat_close_input(AVFormatContext **s)
     * }
     */
    public static MethodHandle avformat_close_input$handle() {
        return avformat_close_input.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void avformat_close_input(AVFormatContext **s)
     * }
     */
    public static MemorySegment avformat_close_input$address() {
        return avformat_close_input.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void avformat_close_input(AVFormatContext **s)
     * }
     */
    public static void avformat_close_input(MemorySegment s) {
        var mh$ = avformat_close_input.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avformat_close_input", s);
            }
            mh$.invokeExact(s);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avcodec_alloc_context3 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_alloc_context3");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AVCodecContext *avcodec_alloc_context3(const AVCodec *codec)
     * }
     */
    public static FunctionDescriptor avcodec_alloc_context3$descriptor() {
        return avcodec_alloc_context3.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AVCodecContext *avcodec_alloc_context3(const AVCodec *codec)
     * }
     */
    public static MethodHandle avcodec_alloc_context3$handle() {
        return avcodec_alloc_context3.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AVCodecContext *avcodec_alloc_context3(const AVCodec *codec)
     * }
     */
    public static MemorySegment avcodec_alloc_context3$address() {
        return avcodec_alloc_context3.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AVCodecContext *avcodec_alloc_context3(const AVCodec *codec)
     * }
     */
    public static MemorySegment avcodec_alloc_context3(MemorySegment codec) {
        var mh$ = avcodec_alloc_context3.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_alloc_context3", codec);
            }
            return (MemorySegment)mh$.invokeExact(codec);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avcodec_free_context {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_free_context");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void avcodec_free_context(AVCodecContext **avctx)
     * }
     */
    public static FunctionDescriptor avcodec_free_context$descriptor() {
        return avcodec_free_context.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void avcodec_free_context(AVCodecContext **avctx)
     * }
     */
    public static MethodHandle avcodec_free_context$handle() {
        return avcodec_free_context.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void avcodec_free_context(AVCodecContext **avctx)
     * }
     */
    public static MemorySegment avcodec_free_context$address() {
        return avcodec_free_context.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void avcodec_free_context(AVCodecContext **avctx)
     * }
     */
    public static void avcodec_free_context(MemorySegment avctx) {
        var mh$ = avcodec_free_context.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_free_context", avctx);
            }
            mh$.invokeExact(avctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avcodec_parameters_to_context {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_parameters_to_context");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int avcodec_parameters_to_context(AVCodecContext *codec, const struct AVCodecParameters *par)
     * }
     */
    public static FunctionDescriptor avcodec_parameters_to_context$descriptor() {
        return avcodec_parameters_to_context.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int avcodec_parameters_to_context(AVCodecContext *codec, const struct AVCodecParameters *par)
     * }
     */
    public static MethodHandle avcodec_parameters_to_context$handle() {
        return avcodec_parameters_to_context.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int avcodec_parameters_to_context(AVCodecContext *codec, const struct AVCodecParameters *par)
     * }
     */
    public static MemorySegment avcodec_parameters_to_context$address() {
        return avcodec_parameters_to_context.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int avcodec_parameters_to_context(AVCodecContext *codec, const struct AVCodecParameters *par)
     * }
     */
    public static int avcodec_parameters_to_context(MemorySegment codec, MemorySegment par) {
        var mh$ = avcodec_parameters_to_context.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_parameters_to_context", codec, par);
            }
            return (int)mh$.invokeExact(codec, par);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avcodec_open2 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_open2");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int avcodec_open2(AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options)
     * }
     */
    public static FunctionDescriptor avcodec_open2$descriptor() {
        return avcodec_open2.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int avcodec_open2(AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options)
     * }
     */
    public static MethodHandle avcodec_open2$handle() {
        return avcodec_open2.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int avcodec_open2(AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options)
     * }
     */
    public static MemorySegment avcodec_open2$address() {
        return avcodec_open2.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int avcodec_open2(AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options)
     * }
     */
    public static int avcodec_open2(MemorySegment avctx, MemorySegment codec, MemorySegment options) {
        var mh$ = avcodec_open2.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_open2", avctx, codec, options);
            }
            return (int)mh$.invokeExact(avctx, codec, options);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avcodec_send_packet {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_send_packet");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int avcodec_send_packet(AVCodecContext *avctx, const AVPacket *avpkt)
     * }
     */
    public static FunctionDescriptor avcodec_send_packet$descriptor() {
        return avcodec_send_packet.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int avcodec_send_packet(AVCodecContext *avctx, const AVPacket *avpkt)
     * }
     */
    public static MethodHandle avcodec_send_packet$handle() {
        return avcodec_send_packet.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int avcodec_send_packet(AVCodecContext *avctx, const AVPacket *avpkt)
     * }
     */
    public static MemorySegment avcodec_send_packet$address() {
        return avcodec_send_packet.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int avcodec_send_packet(AVCodecContext *avctx, const AVPacket *avpkt)
     * }
     */
    public static int avcodec_send_packet(MemorySegment avctx, MemorySegment avpkt) {
        var mh$ = avcodec_send_packet.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_send_packet", avctx, avpkt);
            }
            return (int)mh$.invokeExact(avctx, avpkt);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class avcodec_receive_frame {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("avcodec_receive_frame");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int avcodec_receive_frame(AVCodecContext *avctx, AVFrame *frame)
     * }
     */
    public static FunctionDescriptor avcodec_receive_frame$descriptor() {
        return avcodec_receive_frame.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int avcodec_receive_frame(AVCodecContext *avctx, AVFrame *frame)
     * }
     */
    public static MethodHandle avcodec_receive_frame$handle() {
        return avcodec_receive_frame.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int avcodec_receive_frame(AVCodecContext *avctx, AVFrame *frame)
     * }
     */
    public static MemorySegment avcodec_receive_frame$address() {
        return avcodec_receive_frame.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int avcodec_receive_frame(AVCodecContext *avctx, AVFrame *frame)
     * }
     */
    public static int avcodec_receive_frame(MemorySegment avctx, MemorySegment frame) {
        var mh$ = avcodec_receive_frame.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("avcodec_receive_frame", avctx, frame);
            }
            return (int)mh$.invokeExact(avctx, frame);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_get_pix_fmt_name {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_get_pix_fmt_name");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *av_get_pix_fmt_name(enum AVPixelFormat pix_fmt)
     * }
     */
    public static FunctionDescriptor av_get_pix_fmt_name$descriptor() {
        return av_get_pix_fmt_name.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *av_get_pix_fmt_name(enum AVPixelFormat pix_fmt)
     * }
     */
    public static MethodHandle av_get_pix_fmt_name$handle() {
        return av_get_pix_fmt_name.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *av_get_pix_fmt_name(enum AVPixelFormat pix_fmt)
     * }
     */
    public static MemorySegment av_get_pix_fmt_name$address() {
        return av_get_pix_fmt_name.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *av_get_pix_fmt_name(enum AVPixelFormat pix_fmt)
     * }
     */
    public static MemorySegment av_get_pix_fmt_name(int pix_fmt) {
        var mh$ = av_get_pix_fmt_name.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_get_pix_fmt_name", pix_fmt);
            }
            return (MemorySegment)mh$.invokeExact(pix_fmt);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_opt_set {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_opt_set");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_opt_set(void *obj, const char *name, const char *val, int search_flags)
     * }
     */
    public static FunctionDescriptor av_opt_set$descriptor() {
        return av_opt_set.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_opt_set(void *obj, const char *name, const char *val, int search_flags)
     * }
     */
    public static MethodHandle av_opt_set$handle() {
        return av_opt_set.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_opt_set(void *obj, const char *name, const char *val, int search_flags)
     * }
     */
    public static MemorySegment av_opt_set$address() {
        return av_opt_set.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_opt_set(void *obj, const char *name, const char *val, int search_flags)
     * }
     */
    public static int av_opt_set(MemorySegment obj, MemorySegment name, MemorySegment val, int search_flags) {
        var mh$ = av_opt_set.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_opt_set", obj, name, val, search_flags);
            }
            return (int)mh$.invokeExact(obj, name, val, search_flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class av_opt_set_int {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_LONG_LONG,
            FFmpeg.C_INT
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("av_opt_set_int");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int av_opt_set_int(void *obj, const char *name, int64_t val, int search_flags)
     * }
     */
    public static FunctionDescriptor av_opt_set_int$descriptor() {
        return av_opt_set_int.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int av_opt_set_int(void *obj, const char *name, int64_t val, int search_flags)
     * }
     */
    public static MethodHandle av_opt_set_int$handle() {
        return av_opt_set_int.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int av_opt_set_int(void *obj, const char *name, int64_t val, int search_flags)
     * }
     */
    public static MemorySegment av_opt_set_int$address() {
        return av_opt_set_int.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int av_opt_set_int(void *obj, const char *name, int64_t val, int search_flags)
     * }
     */
    public static int av_opt_set_int(MemorySegment obj, MemorySegment name, long val, int search_flags) {
        var mh$ = av_opt_set_int.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("av_opt_set_int", obj, name, val, search_flags);
            }
            return (int)mh$.invokeExact(obj, name, val, search_flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int SWS_BILINEAR = (int)2L;
    /**
     * {@snippet lang=c :
     * enum SwsFlags.SWS_BILINEAR = 2
     * }
     */
    public static int SWS_BILINEAR() {
        return SWS_BILINEAR;
    }
    private static final int SWS_AREA = (int)32L;
    /**
     * {@snippet lang=c :
     * enum SwsFlags.SWS_AREA = 32
     * }
     */
    public static int SWS_AREA() {
        return SWS_AREA;
    }

    private static class sws_freeContext {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("sws_freeContext");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void sws_freeContext(SwsContext *swsContext)
     * }
     */
    public static FunctionDescriptor sws_freeContext$descriptor() {
        return sws_freeContext.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void sws_freeContext(SwsContext *swsContext)
     * }
     */
    public static MethodHandle sws_freeContext$handle() {
        return sws_freeContext.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void sws_freeContext(SwsContext *swsContext)
     * }
     */
    public static MemorySegment sws_freeContext$address() {
        return sws_freeContext.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void sws_freeContext(SwsContext *swsContext)
     * }
     */
    public static void sws_freeContext(MemorySegment swsContext) {
        var mh$ = sws_freeContext.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sws_freeContext", swsContext);
            }
            mh$.invokeExact(swsContext);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sws_getContext {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_POINTER,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("sws_getContext");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * SwsContext *sws_getContext(int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, SwsFilter *srcFilter, SwsFilter *dstFilter, const double *param)
     * }
     */
    public static FunctionDescriptor sws_getContext$descriptor() {
        return sws_getContext.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * SwsContext *sws_getContext(int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, SwsFilter *srcFilter, SwsFilter *dstFilter, const double *param)
     * }
     */
    public static MethodHandle sws_getContext$handle() {
        return sws_getContext.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * SwsContext *sws_getContext(int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, SwsFilter *srcFilter, SwsFilter *dstFilter, const double *param)
     * }
     */
    public static MemorySegment sws_getContext$address() {
        return sws_getContext.ADDR;
    }

    /**
     * {@snippet lang=c :
     * SwsContext *sws_getContext(int srcW, int srcH, enum AVPixelFormat srcFormat, int dstW, int dstH, enum AVPixelFormat dstFormat, int flags, SwsFilter *srcFilter, SwsFilter *dstFilter, const double *param)
     * }
     */
    public static MemorySegment sws_getContext(int srcW, int srcH, int srcFormat, int dstW, int dstH, int dstFormat, int flags, MemorySegment srcFilter, MemorySegment dstFilter, MemorySegment param) {
        var mh$ = sws_getContext.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sws_getContext", srcW, srcH, srcFormat, dstW, dstH, dstFormat, flags, srcFilter, dstFilter, param);
            }
            return (MemorySegment)mh$.invokeExact(srcW, srcH, srcFormat, dstW, dstH, dstFormat, flags, srcFilter, dstFilter, param);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class sws_scale {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER,
            FFmpeg.C_INT,
            FFmpeg.C_INT,
            FFmpeg.C_POINTER,
            FFmpeg.C_POINTER
        );

        public static final MemorySegment ADDR = FFmpeg.findOrThrow("sws_scale");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int sws_scale(SwsContext *c, const uint8_t *const srcSlice[], const int srcStride[], int srcSliceY, int srcSliceH, uint8_t *const dst[], const int dstStride[])
     * }
     */
    public static FunctionDescriptor sws_scale$descriptor() {
        return sws_scale.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int sws_scale(SwsContext *c, const uint8_t *const srcSlice[], const int srcStride[], int srcSliceY, int srcSliceH, uint8_t *const dst[], const int dstStride[])
     * }
     */
    public static MethodHandle sws_scale$handle() {
        return sws_scale.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int sws_scale(SwsContext *c, const uint8_t *const srcSlice[], const int srcStride[], int srcSliceY, int srcSliceH, uint8_t *const dst[], const int dstStride[])
     * }
     */
    public static MemorySegment sws_scale$address() {
        return sws_scale.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int sws_scale(SwsContext *c, const uint8_t *const srcSlice[], const int srcStride[], int srcSliceY, int srcSliceH, uint8_t *const dst[], const int dstStride[])
     * }
     */
    public static int sws_scale(MemorySegment c, MemorySegment srcSlice, MemorySegment srcStride, int srcSliceY, int srcSliceH, MemorySegment dst, MemorySegment dstStride) {
        var mh$ = sws_scale.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("sws_scale", c, srcSlice, srcStride, srcSliceY, srcSliceH, dst, dstStride);
            }
            return (int)mh$.invokeExact(c, srcSlice, srcStride, srcSliceY, srcSliceH, dst, dstStride);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final long AV_NOPTS_VALUE = -9223372036854775808L;
    /**
     * {@snippet lang=c :
     * #define AV_NOPTS_VALUE -9223372036854775808
     * }
     */
    public static long AV_NOPTS_VALUE() {
        return AV_NOPTS_VALUE;
    }
    private static final int AVERROR_EOF = (int)-541478725L;
    /**
     * {@snippet lang=c :
     * #define AVERROR_EOF -541478725
     * }
     */
    public static int AVERROR_EOF() {
        return AVERROR_EOF;
    }
    private static final int AV_LOG_QUIET = (int)-8L;
    /**
     * {@snippet lang=c :
     * #define AV_LOG_QUIET -8
     * }
     */
    public static int AV_LOG_QUIET() {
        return AV_LOG_QUIET;
    }
    private static final int AV_DISPOSITION_ATTACHED_PIC = (int)1024L;
    /**
     * {@snippet lang=c :
     * #define AV_DISPOSITION_ATTACHED_PIC 1024
     * }
     */
    public static int AV_DISPOSITION_ATTACHED_PIC() {
        return AV_DISPOSITION_ATTACHED_PIC;
    }
}

